#!/bin/sh -f
#PBS -N SB2_61x241_np1x5_T21_Save1500
#PBS -q batch
#PBS -l nodes=cu04:ppn=5

source /opt/intel/composer_xe_2015/bin/compilervars.sh intel64
source /opt/intel/composer_xe_2015.1.133/mkl/bin/intel64/mklvars_intel64.sh
source /opt/intel/impi/5.0.2.044/intel64/bin/mpivars.sh

cd $PBS_O_WORKDIR
cat $PBS_NODEFILE > /$PBS_O_WORKDIR/nodefile

date
mpirun -hosts cu04 -np 5 ./openNS2d.out > log
date

exit

